packages:
  - packages/*
  - demos/*
  - guides/*
  - docs

onlyBuiltDependencies:
  - sharp

overrides:
  rollup@<2.79.2: '>=2.79.2'
  esbuild@<=0.24.2: '>=0.25.0'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
