packages:
  - packages/*
  - demos/*
  - guides/*
  - docs

onlyBuiltDependencies:
  - sharp

overrides:
  rollup@<2.79.2: '>=2.79.2'
  esbuild@<=0.24.2: '>=0.25.0'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  next@>=15.3.0 <15.3.3: '>=15.3.3'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  on-headers@<1.1.0: '>=1.1.0'
  tmp@<=0.2.3: '>=0.2.4'
