---
name: "check changelog"
on:
  pull_request:
    paths:
      - "tools/codegen/**"
      - ".github/workflows/codegen_changelog.yaml"
      - ".github/workflows/wf_check_changelog.yaml"
      - 'flake.nix'
      - 'flake.lock'
      - 'nix/**'

jobs:
  check-changelog:
    uses: ./.github/workflows/wf_check_changelog.yaml
    needs:
      - check-permissions
    with:
      PROJECT_PATH: tools/codegen
