---
name: "check changelog"
on:
  pull_request:
    paths:
      - ".github/workflows/nhost-js_changelog.yaml"
      - ".github/workflows/wf_check_changelog.yaml"
      - "packages/nhost-js/**"
      - 'flake.nix'
      - 'flake.lock'
      - 'nix/**'

jobs:
  check-changelog:
    uses: ./.github/workflows/wf_check_changelog.yaml
    with:
      PROJECT_PATH: packages/nhost-js
