---
on:
  workflow_call:
    inputs:
      PROJECT_PATH:
        type: string
        required: true
        description: "Path to the project directory where CHANGELOG.md is located"

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Check CHANGELOG.md and verify PR title"
        run: |
          # Fetch the default branch
          git fetch origin ${{ github.base_ref || 'main' }}

          # Check if CHANGELOG.md exists
          if [ ! -f "${{ inputs.PROJECT_PATH }}/CHANGELOG.md" ]; then
            echo "::error::CHANGELOG.md does not exist in ${{ inputs.PROJECT_PATH }}"
            exit 1
          fi
          
          # Validate PR title format
          PR_TITLE="${{ github.event.pull_request.title }}"
          if ! echo "$PR_TITLE" | grep -Eq "^(feat|fix|chore) \([a-zA-Z0-9_/-]+\): .+$"; then
            echo "::error::PR title '$PR_TITLE' does not follow the required format: 'feat|fix|chore (affected-service): this is the title'"
            exit 1
          fi

          # Get the diff for CHANGELOG.md
          git diff origin/${{ github.base_ref || 'main' }} -- ${{ inputs.PROJECT_PATH }}/CHANGELOG.md > changelog_diff.txt

          # Extract PR number
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          # Create the expected CHANGELOG entry format with PR title and number
          EXPECTED_ENTRY="$PR_TITLE #$PR_NUMBER"
          
          # Check if PR title with PR number appears in the diff
          if grep -q "$EXPECTED_ENTRY" changelog_diff.txt; then
            echo "PR title with PR number found in ${{ inputs.PROJECT_PATH}}/CHANGELOG.md diff"
          else
            echo "::error::Expected entry '$EXPECTED_ENTRY' not found in ${{ inputs.PROJECT_PATH }}/CHANGELOG.md diff"
            echo "::error::Please add your PR title with PR number to CHANGELOG.md (Example: 'feat (myservice): something something #$PR_NUMBER')"
            exit 1
          fi
